Use practices from REDCap

diff --git a/etl/scripts/etl_redcapToPortal_practiceDetails.template b/etl/scripts/etl_redcapToPortal_practiceDetails.template
--- a/etl/scripts/etl_redcapToPortal_practiceDetails.template
+++ b/etl/scripts/etl_redcapToPortal_practiceDetails.template
@@ -23,5 +23,14 @@ fi
 
 rm "$tmpfile"
 
+# Register New Practices
+envsubst < /scripts/sql/etl_portal_registerNewPracticeDetails.sql | mysql  -h mysql -u $PORTAL_MYSQL_USER -p$PORTAL_MYSQL_PASSWORD $PORTAL_MYSQL_DATABASE
+
+if [ $? -ne 0 ]; then
+    echo "$0 failed registering new practices"
+    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+    exit 1
+fi
+
 echo "$0 Completed: $(date)"
 echo "------------------------------------"
